# config/meta.yml
meta_product_name: "Fidelis"
meta_title: "Fidelis - Shop local, love local "
meta_description: "Connecting locals to their favorite shops. Our digital loyalty punchcards keep customers coming back for more rewards."
meta_image: "cover.png" # should exist in `app/assets/images/`


